unit constants;

interface

const
  CAMPO_COMPROVANTE_CLIENTE = 121;
  CAMPO_COMPROVANTE_ESTAB = 122;

  CONFIG_OK = 0;
  CONFIG_ERROR_INVALID_SITEF_ADDRESS = 1;
  CONFIG_ERROR_INVALID_STORE_ID = 2;
  CONFIG_ERROR_INVALID_TERMINAL_ID = 3;
  CONFIG_ERROR_MISSING_COLLECT_FUNCTION = 4;
  CONFIG_ERROR_MISSING_RECEIVE_FUNCTION = 5;
  CONFIG_ERROR_TCPIP_SETUP = 6;
  CONFIG_ERROR_OUT_OF_MEMORY = 7;
  CONFIG_ERROR_CLISITEF_LIBRARY_NOT_FOUND = 8;
  CONFIG_ERROR_MAX_SITEF_IP_REACHED = 9;
  CONFIG_ERROR_INITIALIZING_FILES = 10;
  CONFIG_ERROR_INVALID_FIELD = 11;
  CONFIG_ERROR_SECURE_MODE = 12;
  CONFIG_ERROR_INVALID_PATH = 13;

  CMD_RESULT_DATA = 0;
  CMD_SHOW_MSG_CASHIER = 1;
  CMD_SHOW_MSG_CUSTOMER = 2;
  CMD_SHOW_MSG_CASHIER_CUSTOMER = 3;
  CMD_SHOW_MENU_TITLE = 4;
  CMD_CLEAR_MSG_CASHIER = 11;
  CMD_CLEAR_MSG_CUSTOMER = 12;
  CMD_CLEAR_MSG_CASHIER_CUSTOMER = 13;
  CMD_CLEAR_MENU_TITLE = 14;
  CMD_SHOW_HEADER = 15;
  CMD_CLEAR_HEADER = 16;
  CMD_CONFIRM_GO_BACK = 19;
  CMD_CONFIRMATION = 20;
  CMD_GET_MENU_OPTION = 21;
  CMD_PRESS_ANY_KEY = 22;
  CMD_ABORT_REQUEST = 23;
  CMD_GET_FIELD_INTERNAL = 29;
  CMD_GET_FIELD = 30;
  CMD_GET_FIELD_CHEQUE = 31;
  CMD_GET_FIELD_TRACK = 32;
  CMD_GET_FIELD_PASSWORD = 33;
  CMD_GET_FIELD_CURRENCY = 34;
  CMD_GET_FIELD_BARCODE = 35;
  CMD_GET_PINPAD_CONFIRMATION = 37;
  CMD_GET_MASKED_FIELD = 41;

  EVT_BEGIN_BT_STARTUP = 1;
  EVT_END_BT_STARTUP = 2;
  EVT_BEGIN_PP_CONNECT = 3;
  EVT_END_PP_CONNECT = 4;
  EVT_BEGIN_PP_CONFIG = 5;
  EVT_END_PP_CONFIG = 6;
  EVT_BT_PP_DISCONNECT = 7;

  CMD_RETORNO_VALOR = 0;
  CMD_MENSAGEM_OPERADOR = 1;
  CMD_MENSAGEM_CLIENTE = 2;
  CMD_MENSAGEM = 3;
  CMD_TITULO_MENU = 4;
  CMD_REMOVE_MENSAGEM_OPERADOR = 11;
  CMD_REMOVE_MENSAGEM_CLIENTE = 12;
  CMD_REMOVE_MENSAGEM = 13;
  CMD_REMOVE_TITULO_MENU = 14;
  CMD_EXIBE_CABECALHO = 15;
  CMD_REMOVE_CABECALHO = 16;
  CMD_CONFIRMA_CANCELA = 20;
  CMD_SELECIONA_MENU = 21;
  CMD_OBTEM_QUALQUER_TECLA = 22;
  CMD_PERGUNTA_SE_INTERROMPE = 23;
  CMD_OBTEM_CAMPO_SEM_COLETA = 29;
  CMD_OBTEM_CAMPO = 30;
  CMD_OBTEM_CHEQUE = 31;
  CMD_OBTEM_VALOR = 34;
  CMD_OBTEM_CODIGO_EM_BARRAS = 35;
  CMD_PINPAD_LE = 40;
  CMD_NUMERIO_PARCELAS = 505;

  EVT_INICIA_ATIVACAO_BT = 1;
  EVT_FIM_ATIVACAO_BT = 2;
  EVT_INICIA_AGUARDA_CONEXAO_PP = 3;
  EVT_FIM_AGUARDA_CONEXAO_PP = 4;
  EVT_PP_BT_CONFIGURANDO = 5;
  EVT_PP_BT_CONFIGURADO = 6;
  EVT_PP_BT_DESCONECTADO = 7;
  EVT_INICIO_MODO_DISCOVER_BT = 9;
  EVT_FIM_MODO_DISCOVER_BT = 16;
  EVT_CONTINUA_CADASTRO_PIN_BT = 17;
  EVT_SUCESSO_CADASTRO_PIN_BT = 32;
  EVT_FALHA_CADASTRO_PIN_BT = 33;

  PPBT_CMD_CONFIGURA_BIBLIOTECA = 0;
  PPBT_CMD_TRACE = 80;

  PPI_CMD_VERIFICA_PRESENCA_PINPAD = 1;
  PPI_CMD_ESCREVE_MENSAGEM_PERMANENTE = 2;
  PPI_CMD_LE_SIM_NAO_PINPAD = 3;
  PPI_CMD_GET_INFO = 4;
  PPI_CMD_LE_CARTAO_SEGURO = 5;
  PPI_CMD_LE_SENHA = 6;

  CAMPO_FORNECA_CODIGO_SUPERVISOR = 30;
  CAMPO_PINPAD_ABRE = 650;
  CAMPO_PINPAD_FECHA = 651;
  CAMPO_PINPAD_ABORTA = 652;
  CAMPO_PINPAD_ESCREVE = 653;
  CAMPO_PINPAD_LE = 654;
  CAMPO_TIPO_CONEXAO_PINPAD = 671;
  CAMPO_RESULTADO_FUNCAO = 2150;
  CAMPO_CONEXAOEXT_SITEF_IP = 2422;
  CAMPO_CONEXAOEXT_SITEF_PORTA = 2423;
  CAMPO_CONEXAOEXT_SITEF_TIPO = 2424;
  CAMPO_CONEXAOEXT_CONECTA = 2425;
  CAMPO_CONEXAOEXT_DESCONECTA = 2426;
  CAMPO_CONEXAOEXT_ENVIA_RECEBE = 2427;
  CAMPO_CONEXAOEXT_SENHA_CERTIFICADO = 2428;
  CAMPO_UUID_ANDROID = 4094;
  CAMPO_FINALIZA_TRANSACAO = 5005;

  CAMPO_TIPO_CARTAO = 132;
  CAMPO_TIPO_CARTAO_LIDO = 2090;

  CAMPO_NSU_SITEF = 133;
  CAMPO_NSU_HOST = 134;

  CAMPO_CODIGO_REDE = 131;
  CAMPO_CODIGO_BANDEIRA = 132;
  CAMPO_CODIGO_AUTORIZACAO = 135;

  CAMPO_BIN = 136;
  CAMPO_CODIGO_REDE_AUTORIZADORA = 158;
  CAMPO_CODIGO_ADMINISTRADORA = 1108;
  CAMPO_NOME_TITULAR = 1134;
  CAMPO_NUMERO_CUPOM = 160;
  CAMPO_DATA_FISCAL = 605;
  CAMPO_EMBOSO = 1190;
  CAMPO_DATA_HORA_SITEF = 105;
  CAMPO_CODIGO_RESPOSTA_AUTORIZADOR = 2010;
  CAMPO_NOME_DA_INSTITUICAO = 156;

  CAMPO_SERIE_PINPAD = 2455;

  CAMPO_NSU_TRANSACAO_ORIGINAL_CANCELAMENTO = 620;

  TXT_SITEF_CONECTADO = 'SiTef Conectado';
  TXT_SITEF_CONECTANDO = 'Conectando Sitef';
  TXT_SITEF_INSIRAOUPASSEOCARTAO = 'Insira ou passe o cartão na leitora';

  CDB_DEBITO = 'DEBITO VAREJO';
  CCR_CREDITO_A_VISTA = 'CREDITO A VISTA VAREJO';
  CCR_CREDITO_PARCELADO_ESTABELECIMENTO = 'PARC VAREJO - ESTABELECIMENTO';
  CCR_CREDITO_PARCELADO_TITULAR = 'PARC VAREJO - TITULAR';
  CCR_CREDITO_PARCELADO_TITULAR_LADO = 'PINPAG - LADO A LADO';
  CCR_CREDITO_DETRAN_MG = 'DETRAN MG';
  CDB_DEBITO_AUXILIO_EMERGENCIAL = 'DEBITO VAREJO - AUXILIO';

  ARQUIVO_EQUIPAMENTO = 'equipamento.json';
  ARQUIVO_AUTENTICACAO = 'autenticacao.json';
  ARQUIVO_OPERACAO_RETORNO = 'operacao_retorno.json';
  ARQUIVO_OPERACAO_CONSULTA = 'operacao_consulta.json';
  ARQUIVO_OPERACAO_CANCELAMENTO = 'operacao_cancelamento.json';
  ARQUIVO_OPERACAO_ITEM = 'operacao_item.json';
  ARQUIVO_SERVICOS = 'servicos.json';
  ARQUIVO_RETORNOS = 'retornos.json';
  ARQUIVO_AUTH = 'auth.json';
  ARQUIVO_PARCELAMENTO_ITEM = 'parcelamento_item.json';
  ARQUIVO_PARCELAMENTO_RETORNO = 'parcelamento_retorno.json';
  ARQUIVO_RELATORIO_FECHAMENTO = 'relatorio.json';
  ARQUIVO_MOBILE_POS = 'mobilepos.json';

  FORMAPAGAMENTO_DEBITO = 2;
  FORMAPAGAMENTO_CREDITO = 3;
  FORMAPAGAMENTO_CANCELAMENTO = 200;
  FORMAPAGAMENTO_CANCELAMENTO_CARTAO_CREDITO = 210;
  FORMAPAGAMENTO_CANCELAMENTO_CARTAO_DEBITO = 211;
  FORMAPAGAMENTO_REIMPRESSAO = 57;
  FORMAPAGAMENTO_CARTAO_CREDITO = 'CCR';
  FORMAPAGAMENTO_CARTAO_DEBITO = 'CDB';

  HTTP_RESULT_SUCESSO = 200;
  HTTP_RESULT_ERRO = 400;


implementation

end.
